---
title: "nested hierarchical regression"
author: "Bindoff, A."
date: "9 July 2018"
output: html_document
---


https://rpubs.com/kaz_yos/stan-multi-2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Random intercept model

Level 1 model: $Y_{ijk} = \beta_{0jk} + \beta_{1}X_{1ijk} + e_{0ijk}$  

Level 1 errors: $e_{0ijk} \sim N(0, \sigma^2_{e0})$  

Level 2 model:  $\beta_{0jk} = \beta_{0k} + u_{0jk}$  

Level 2 errors: $u_{0jk} \sim N(0, \sigma^2_{u_{0jk}})$  

Level 3 model:  $\beta_{0k} = \beta_0 + u_{0k}$  

Level 3 errors:  $u_{0k} \sim N(0, \sigma^2_{u_{0k}})$

### Data generation  

```{r  data_gen}
set.seed(201503031)

## Population intercept
beta_0    <- 3
## Population slope
beta_1    <- 1.5

## Level-1 errors
sigma_e0  <- 3
e_0ijk    <- rnorm(n = 10*10*10, mean = 0, sd = sigma_e0)
level1    <- seq_len(10*10*10)

## Level-2 errors
sigma_u0jk <- 2
u_0jk     <- rnorm(n = 10*10, mean = 0, sd = sigma_u0jk)
level2    <- rep(seq_len(10*10), each = 10)

## Level-3 errors
sigma_u0k  <- 1
u_0k      <- rnorm(n = 10, mean = 0, sd = sigma_u0k)
level3    <- rep(seq_len(10), each = 100)

## Varying intercepts
## Level 3 (repeat for level 2)
beta_0k   <- rep(beta_0 + u_0k, each = 10)
## Level 2 (repeat for level 1)
beta_0jk  <- rep(beta_0k + u_0jk, each = 10)

## Predictor
X_1ijk    <- runif(n = 1000, min = 0, max = 100)

## Outcome
Y_ijk     <- beta_0jk + beta_1*X_1ijk + e_0ijk

## Combine
dat       <- list(Ni          = length(unique(level1)),
                  Nj          = length(unique(level2)),
                  Nk          = length(unique(level3)),
                  level2      = level2,
                  level3      = level3,
                  lev3ForLev2 = rep(seq_len(10), each = 10),
                  Y_ijk       = Y_ijk,
                  X_1ijk      = X_1ijk)


```


```{r stancode}

stancode <- 'data {
  // Define variables in data
  // Number of level-1 observations (an integer)
  int<lower=0> Ni;
  // Number of level-2 clusters
  int<lower=0> Nj;
  // Number of level-3 clusters
  int<lower=0> Nk;

  // Cluster IDs
  int<lower=1> level2[Ni];
  int<lower=1> level3[Ni];
  int<lower=1> lev3ForLev2[Nj];

  // Continuous outcome
  real Y_ijk[Ni];
  // Continuous predictor
  real X_1ijk[Ni];
}

parameters {
  // Define parameters to estimate
  // Population intercept (a real number)
  real beta_0;
  // Population slope
  real beta_1;

  // Level-1
  real<lower=0> sigma_e0;

  // Level-2 random effect
  real u_0jk[Nj];
  real<lower=0> sigma_u0jk;

  // Level-3 random effect
  real u_0k[Nk];
  real<lower=0> sigma_u0k;
}

transformed parameters  {
  // Varying intercepts
  real beta_0jk[Nj];
  real beta_0k[Nk];

  // Individual mean
  real mu[Ni];

  // Varying intercepts definition
  // Level-3 (10 level-3 random intercepts)
  for (k in 1:Nk) {
    beta_0k[k] <- beta_0 + u_0k[k];
  }
  // Level-2 (100 level-2 random intercepts)
  for (j in 1:Nj) {
    beta_0jk[j] <- beta_0k[lev3ForLev2[j]] + u_0jk[j];
  }
  // Individual mean
  for (i in 1:Ni) {
    mu[i] <- beta_0jk[level2[i]] + beta_1 * X_1ijk[i];
  }
}

model {
  // Prior part of Bayesian inference
  // Flat prior for mu (no need to specify if non-informative)

  // Random effects distribution
  u_0k  ~ normal(0, sigma_u0k);
  u_0jk ~ normal(0, sigma_u0jk);

  // Likelihood part of Bayesian inference
  // Outcome model N(mu, sigma^2) (use SD rather than Var)
  for (i in 1:Ni) {
    Y_ijk[i] ~ normal(mu[i], sigma_e0);
  }
}'

```


```{r sample}
resStan <- stan(model_code = stancode, data = dat,
                chains = 3, iter = 3000, warmup = 500, thin = 10)

resStanExt <- rstan::extract(resStan, permuted = TRUE)
rstan::traceplot(resStan, pars = c("beta_0","beta_1","sigma_e0","sigma_u0jk","sigma_u0k"), inc_warmup = FALSE)


print(resStan, pars = c("beta_0","beta_1","sigma_e0","sigma_u0jk","sigma_u0k"))

```


### lmer


```{r}
library(lme4)
resLmer <- lmer(Y_ijk ~ X_1ijk + (1 | level3/level2))
varCorrMat <- as.data.frame(VarCorr(resLmer))
summary(resLmer)

```


### Comparison

```{r}
## True
resDf <- data.frame(beta_0     = c(beta_0,     median(resStanExt$beta_0),     coef(summary(resLmer))[1,1]),
                    beta_1     = c(beta_1,     median(resStanExt$beta_1),     coef(summary(resLmer))[2,1]),
                    sigma_e0   = c(sigma_e0,   median(resStanExt$sigma_e0),   varCorrMat[3,"sdcor"]),
                    sigma_u0jk = c(sigma_u0jk, median(resStanExt$sigma_u0jk), varCorrMat[1,"sdcor"]),
                    sigma_u0k  = c(sigma_u0k,  median(resStanExt$sigma_u0k),  varCorrMat[2,"sdcor"]))
rownames(resDf) <- c("true","stan","lmer")
print(resDf, digits = 3)

```